### ISSUE TITLE
Fonts installation is hardcoded to jcampbell

### ISSUE THREAD

**Issue by castrojo** [j1mc/ansible-silverblue#1]
Hi Jim, thanks for working on this, I"m hoping to adapt this playbook to my needs. Fonts role doesn't complete unless you're jcampbell. Modifying it to my username completes successfully.

Also should the homedir be: /var/home/$USER?

```
user: jcampbell
homedir: /home/jcampbell
```

**Comment by j1mc** [comment]
This should be resolved in the main branch now. I use ansible's 'gather_facts' to get the user and home directory information now.
