### ISSUE TITLE
Needs to check for rpm-ostree being idle

### ISSUE THREAD

**Issue by castrojo** [j1mc/ansible-silverblue#4]
rpm-ostree immediately checks on boot to do a refresh-md, rendering the playbook useless until that process is done. It tends to not be super-fast, we added [a check](https://github.com/castrojo/ublue/blob/0a24c16022ad4a123624458bd03931d0475c8780/00-install-apps.sh#L34) in ublue to just wait until it's ready.

**Comment by j1mc** [comment]
I'll work on this for the `layered_packages` role. I'll check to see if a refresh-md check is running, and will cancel the check if it is running.

**Comment by j1mc** [comment]
Hi Jorge - this should be done now. You can see how I'm handling it here: https://github.com/j1mc/ansible-silverblue/blob/b449cff0525e6bcd3a530e71539191585ec6e179/roles/layered_packages/tasks/main.yml#L4
