### ISSUE TITLE
How to override a package from the base layer?

### ISSUE THREAD

**Issue by castrojo** [j1mc/ansible-silverblue#5]
This is more of a question than a bug, is there a way in the layered packages task to set override for packages? Use case example is replacing the default Firefox with the one from mozilla's flatpak.

**Comment by j1mc** [comment]
You could create a separate 'stanza' in the layered_packages role:

```- name: Install prescribed set of applications as rpm-ostree layered packages
  community.general.rpm_ostree_pkg:
    name: firefox
    state: absent
    # apply_live: true
  become: yes
  become_method: sudo
  

I don't think it's an override, per se, as you aren't using one version of Firefox instead of another.
