### ISSUE TITLE
Layer downloaded RPMs?

### ISSUE THREAD

**Issue by RodneyBrown** [j1mc/ansible-silverblue#9]
Is there a way to specify an RPM to download (e.g. Dropbox) and have rpm-ostree install it?
I do this manually for Dropbox and Vivaldi Browser...

There is already a Dropbox flatpak but doesn't work very well lately.  So I've resorted to using their RPM again.

**Comment by j1mc** [comment]
Hello! You should be able to do:

`rpm-ostree install <packagename.rpm>`

This method of installation isn't ideal, but I think it should work.

**Comment by j1mc** [comment]
I'm going to close this, but I'll note that you can also include `--apply-live` in the command, and it will make that RPM available within the immediate session (i.e., you won't have to reboot to use your dropbox install). Hope this helps!
